name: 'github_sponsor_flutter'
description: 'A new Flutter project.'
publish_to: 'none'
version: '0.0.0'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  collection: '^1.19.0'
  cupertino_icons: '^1.0.6'
  flutter:
    sdk: 'flutter'
  general_bot_library_project:
    path: '../../../general_bot_library_project/package/general_bot_library_project'
  general_universe: '^0.0.0'
  general_universe_flutter: '^0.0.0'
  github_sponsor_scheme:
    path: '../github_sponsor_scheme'
  http: '^1.3.0'
  mime: '^2.0.0'
  packagex: '^0.0.0'
  path: '^1.9.0'
dev_dependencies:
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: 'flutter'
  msix: '^3.16.7'
flutter:
  uses-material-design: true
  fonts:
    - family: 'Pacifico'
      fonts:
        - asset: 'assets/fonts/Pacifico-Regular.ttf'
    - family: 'ShadowsIntoLight'
      fonts:
        - asset: 'assets/fonts/ShadowsIntoLight-Regular.ttf'
packagex:
  name: 'github_sponsor_flutter'
  dart_target: 'github_sponsor_flutter'
  flutter_target: 'main'
  dart_name: 'github_sponsor_flutter'
  flutter_name: 'github_sponsor_flutter'
  is_without_platform_name: true
  flutter_commands:
    obfuscate: true
    split-debug-info: '0.0.0'
    build-name: '0.0.0'
    build-number: 1
    split-per-abi: true
    no-tree-shake-icons: true
  project_id: 'azkadev.packagex'
  github_username: 'azkadev'
  github_is_org: false
msix_config:
  display_name: 'github_sponsor_flutter'
  install_certificate: false
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
