name: 'github_sponsor'
description: 'A sample command-line application.'
version: '0.0.0'
homepage: 'https://github.com/{main_username_owner}/github_sponsor'
repository: 'https://github.com/{main_username_owner}/github_sponsor'
issue_tracker: 'https://github.com/{main_username_owner}/github_sponsor/issues'
documentation: 'https://github.com/{main_username_owner}/github_sponsor/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/{main_username_owner}'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  github_sponsor_scheme: '^0.0.0'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
